export const CHAT_STREAM_CHUNK_TIMEOUT_MS = 20_000

export const EXTERNAL_LINK_TARGET = '_blank'

export const EXTERNAL_LINK_REL = 'noreferrer noopener'

export const DEFAULT_CHAT_MODEL_ID = 'gpt-4o-mini'

export const CHAT_TEXTAREA_MAX_SCROLL_HEIGHT = 200

export const COMPOSER_ATTACH_POPOVER_WIDTH = 280

export const COMPOSER_ATTACH_POPOVER_HEIGHT = 240

export const COMPOSER_ATTACH_POPOVER_OFFSET = -8

export const SIDEBAR_PROFILE_POPOVER_WIDTH = 240

export const SIDEBAR_PROFILE_POPOVER_HEIGHT = 200

export const SIDEBAR_CHAT_ACTIONS_POPOVER_WIDTH = 152

export const SIDEBAR_CHAT_ACTIONS_POPOVER_HEIGHT = 220