export const DEFAULT_TOAST_DURATION_MS = 3_000

export const DEFAULT_FLOATING_POPOVER_WIDTH = 240

export const DEFAULT_FLOATING_POPOVER_HEIGHT = 180

export const DEFAULT_FLOATING_POPOVER_OFFSET = 8

export const FLOATING_POPOVER_VIEWPORT_GAP = 8

export const FLOATING_POPOVER_MIN_WIDTH = 120